[toolchain]
anchor_version = "1.0.0-rc.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
mock_verifier = "4T8nxeiE9c4x55cPhXbqr1rzwXvggLTZkUfDGoSb9yrJ"
private_transfers = "2QRZu5cWy8x8jEFc9nhsnrnQSMAKwNpiLpCXrMRb3oUn"
sunspot_verifier = "CU2Vgym4wiTNcJCuW6r7DV6bCGULJxKdwFjfGfmksSVZ"

[programs.localnet]
mock_verifier = "4T8nxeiE9c4x55cPhXbqr1rzwXvggLTZkUfDGoSb9yrJ"
private_transfers = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
sunspot_verifier = "CU2Vgym4wiTNcJCuW6r7DV6bCGULJxKdwFjfGfmksSVZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "CU2Vgym4wiTNcJCuW6r7DV6bCGULJxKdwFjfGfmksSVZ"
program = "target/deploy/sunspot_verifier.so"
