[toolchain]
anchor_version = "1.0.0-rc.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
mock_verifier = "E5PrYyzzcUptVMNkKV3fRw1bVn1Ma4zCrH4tyktnrbF5"
private_transfers = "Fenf6dTx3REwt6U1QBNzXC1UMva7BukRcN17n3hhShYY"
sunspot_verifier = "DCybqMyoiEjRoBsLEXyLcfxJ88sDCEYVCZ7nsKFYy6EZ"

[programs.localnet]
mock_verifier = "4T8nxeiE9c4x55cPhXbqr1rzwXvggLTZkUfDGoSb9yrJ"
private_transfers = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
sunspot_verifier = "Amugr8yL9EQVAgGwqds9gCmjzs8fh6H3wjJ3eB4pBhXV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "Amugr8yL9EQVAgGwqds9gCmjzs8fh6H3wjJ3eB4pBhXV"
program = "target/deploy/sunspot_verifier.so"
