[package]
name = "merkle_hasher"
type = "bin"
authors = [""]
# NOTE: Requires nargo 1.0.0-beta.13 for Sunspot compatibility
compiler_version = ">=1.0.0"

[dependencies]
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
